In [1]:
from sklearn.datasets import fetch_california_housing

In [2]:
dataset=fetch_california_housing()

In [3]:
dataset

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [4]:
print(dataset.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived

In [5]:
dataset.data

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [6]:
dataset.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [7]:
dataset.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [8]:
import pandas as pd

In [9]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [10]:
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [11]:
df['Price']=dataset.target

In [12]:
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  Price  
0    -122.23  4.526  
1    -122.22  3.585  
2    -122.24  3.521  
3    -122.25  3.413  
4    -122.25  3.422

In [13]:
df.describe()

MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000   
mean       3.870671     28.639486      5.429000      1.096675   1425.476744   
std        1.899822     12.585558      2.474173      0.473911   1132.462122   
min        0.499900      1.000000      0.846154      0.333333      3.000000   
25%        2.563400     18.000000      4.440716      1.006079    787.000000   
50%        3.534800     29.000000      5.229129      1.048780   1166.000000   
75%        4.743250     37.000000      6.052381      1.099526   1725.000000   
max       15.000100     52.000000    141.909091     34.066667  35682.000000   

           AveOccup      Latitude     Longitude         Price  
count  20640.000000  20640.000000  20640.000000  20640.000000  
mean       3.070655     35.631861   -119.569704      2.068558  
std       10.386050      2.135952      2.003532      1.153956  
min        0.692308     32.540000   -124.350000      0.149990  
25%        2.429741     33.930000   -121.800000      1.196000  
50%        2.818116     34.260000   -118.490000      1.797000  
75%        3.282261     37.710000   -118.010000      2.647250  
max     1243.333333     41.950000   -114.310000      5.000010

In [14]:
df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
Price         0
dtype: int64

In [15]:
import seaborn as sns

In [16]:
df_copy=df.sample(frac=0.25)

In [17]:
df_copy.shape

(5160, 9)

## Divide the dataset into independent and dependent datasets.

In [18]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [20]:
from sklearn.model_selection import train_test_split

In [22]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [23]:
X_train.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
5088   0.9809      19.0  3.187726   1.129964       726.0  2.620939     33.98   
17096  4.2232      33.0  6.189696   1.086651      1015.0  2.377049     37.46   
5617   3.5488      42.0  4.821577   1.095436      1044.0  4.331950     33.79   
20060  1.6469      24.0  4.274194   1.048387      1686.0  4.532258     35.87   
895    3.9909      14.0  4.608303   1.089350      2738.0  2.471119     37.54   

       Longitude  
5088     -118.28  
17096    -122.23  
5617     -118.26  
20060    -119.26  
895      -121.96

In [24]:
X.shape

(20640, 8)

In [25]:
X_train.shape,X_test.shape

((13828, 8), (6812, 8))

Feature Scaling--Standardization

In [27]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [28]:
scaler.fit(X_train)

StandardScaler()

In [30]:
X_train=scaler.fit_transform(X_train)

In [31]:
X_train

array([[-1.52169954, -0.75868455, -0.91813082, ..., -0.04014979,
        -0.78315293,  0.65090402],
       [ 0.18205382,  0.3523991 ,  0.30748451, ..., -0.05943619,
         0.8475975 , -1.31911678],
       [-0.17232772,  1.06666717, -0.25107784, ...,  0.09515433,
        -0.87218816,  0.66087881],
       ...,
       [-0.49518065,  0.59048846, -0.59192622, ...,  0.01608523,
        -0.75972261,  0.60103008],
       [ 0.96816708, -1.07613702,  0.39144665, ...,  0.0039722 ,
         0.90383028, -1.18445713],
       [-0.68377427,  1.86029835, -0.83041358, ..., -0.08065717,
         0.9928655 , -1.41387727]])

In [33]:
X_test=scaler.transform(X_test)

In [34]:
X_test

array([[-1.15370815, -0.28250584, -0.50803348, ...,  0.05921216,
         0.19154848,  0.28682423],
       [-0.70700034,  0.11430975, -0.16215378, ..., -0.03549556,
        -0.23956945,  0.06239148],
       [-0.20842797,  1.86029835, -0.59583032, ..., -0.13983657,
         1.0069237 , -1.42385206],
       ...,
       [-0.02167353, -1.07613702,  0.40141018, ...,  0.03744641,
         1.43335556, -0.90516304],
       [ 0.27275111, -1.47295261,  0.29311784, ...,  0.0519346 ,
        -0.73160623,  1.09478213],
       [-0.59570436,  1.78093523, -0.64482761, ..., -0.06665881,
         0.99755157, -1.43881424]])

In [35]:
from sklearn.linear_model import LinearRegression

In [36]:
regression=LinearRegression()

In [37]:
regression.fit(X_train,y_train)

LinearRegression()

In [38]:
regression.coef_

array([ 8.46603472e-01,  1.20333548e-01, -2.98800785e-01,  3.47243173e-01,
       -8.81413334e-05, -4.17242067e-02, -8.94420371e-01, -8.70401317e-01])

In [39]:
regression.intercept_

2.0666362048018536

## Prediction

In [41]:
Y_pred=regression.predict(X_test)

In [45]:
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [47]:
import numpy as np
mse=mean_squared_error(y_test,Y_pred)
print(mse)
mae=mean_absolute_error(y_test,Y_pred)
print(mae)
print(np.sqrt(mse))


0.536968654337246
0.5295710106684453
0.7327814505957735


In [48]:
from sklearn.metrics import r2_score

In [50]:
score=r2_score(y_test,Y_pred)

## Adjusted R-squared

In [51]:
1-(1-score)*(len(y)-1)/(len(y)-X.shape[1]-1)

0.5968931623477872

In [52]:
score

0.5970494128783952

In [53]:
from sklearn.linear_model import Ridge
ridge=Ridge()
ridge.fit(X_train,y_train)

Ridge()

In [54]:
Y_pred=ridge.predict(X_test)

In [55]:
Y_pred

array([0.7260455 , 1.76629798, 2.70503652, ..., 1.25857212, 1.66710506,
       2.2579446 ])

In [56]:
import numpy as np
mse=mean_squared_error(y_test,Y_pred)
print(mse)
mae=mean_absolute_error(y_test,Y_pred)
print(mae)
print(np.sqrt(mse))

0.5369457054801817
0.5295668709657074
0.7327657916962157


In [59]:
from sklearn.linear_model import ElasticNet

In [61]:
elasticnet=ElasticNet(alpha=20.0)
elasticnet.fit(X_train,y_train)

ElasticNet(alpha=20.0)

In [62]:
df_copy.corr()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  \
MedInc      1.000000 -0.108924  0.338323  -0.084194    0.013707  0.006950   
HouseAge   -0.108924  1.000000 -0.170705  -0.095599   -0.293301  0.008851   
AveRooms    0.338323 -0.170705  1.000000   0.820820   -0.077917 -0.008672   
AveBedrms  -0.084194 -0.095599  0.820820   1.000000   -0.080109 -0.007591   
Population  0.013707 -0.293301 -0.077917  -0.080109    1.000000  0.053389   
AveOccup    0.006950  0.008851 -0.008672  -0.007591    0.053389  1.000000   
Latitude   -0.089776  0.013482  0.121313   0.086561   -0.109611  0.016318   
Longitude  -0.006148 -0.113589 -0.027258   0.011236    0.095809  0.008204   
Price       0.684985  0.102709  0.146849  -0.071110   -0.005857 -0.040260   

            Latitude  Longitude     Price  
MedInc     -0.089776  -0.006148  0.684985  
HouseAge    0.013482  -0.113589  0.102709  
AveRooms    0.121313  -0.027258  0.146849  
AveBedrms   0.086561   0.011236 -0.071110  
Population -0.109611   0.095809 -0.005857  
AveOccup    0.016318   0.008204 -0.040260  
Latitude    1.000000  -0.921321 -0.150901  
Longitude  -0.921321   1.000000 -0.042260  
Price      -0.150901  -0.042260  1.000000